[package]
name = "watershot"
authors = ["Kirottu"]
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0"
wgpu_text = "0"

nix = { version = "0.27.1", default-features = false, features = ["process"] }
wayland-client = { version = "0" }
wayland-backend = { version = "0", features = ["client_system"] }
smithay-client-toolkit = "0"
# In order to use nix 0.27.1, same as libwayshot
wl-clipboard-rs = { git = "https://github.com/YaLTeR/wl-clipboard-rs" }

image = { version = "0", default-features = false, features = ["pnm", "farbfeld", "jpeg", "jpeg_rayon", "png", "webp-encoder"] }
ron = "0"
serde = { version = "1", features = ["derive"] }
fontconfig = "0"
clap = { version = "4", features = ["derive"] }
chrono = "0"
env_logger = { version = "0", default-features = false, features = ["auto-color"] }
log = "0"
pollster = "0"
bytemuck = { version = "1", features = ["derive"] }
regex = "1"
hyprland = "0"
strum = { version = "0", features = ["derive", "strum_macros"] }

# wayshot_connection.screenshot_all doesn't return DynamicImage in 0.3.0
libwayshot = { git = "https://github.com/waycrate/wayshot" }
