[package]
name = "watershot"
authors = ["Kirottu"]
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17.0"
raw-window-handle = "0.5.2"
wgpu_text = "0.8.3"

smithay-client-toolkit = "0.17.0"
wayland-backend = { version = "0.1.2", features = ["client_system"] }
wayland-client = { version = "0.30.2", features = ["calloop"] }
wl-clipboard-rs = "0.7.0"
nix = { version = "0.26.1", default-features = false, features = ["process"] }

image = { version = "0", default-features = false, features = ["pnm", "farbfeld", "jpeg", "jpeg_rayon", "png", "webp-encoder"] }
ron = "0"
serde = { version = "1", features = ["derive"] }
fontconfig = "0"
clap = { version = "4", features = ["derive"] }
chrono = "0"
env_logger = { version = "0", default-features = false, features = ["auto-color"] }
log = "0"
pollster = "0"
bytemuck = { version = "1", features = ["derive"] }
regex = "1"
hyprland = "0"
strum = { version = "0", features = ["derive", "strum_macros"] }
